### ISSUE TITLE
`Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 2 out of bounds for length 2`, passando `var` com menos valores do lado direito em relação ao lado esquerdo

### ISSUE THREAD

**Issue by leonelsanchesdasilva** [potigol/potigol#60]
Teste:

```
var a, b, c := 1, 2
```

Resultado:

```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 2 out of bounds for length 2
        at br.edu.ifrn.potigol.M.declVariavelMult(M.java:234)
        at br.edu.ifrn.potigol.Listener.exitDecl_var_multipla(Listener.java:402)
        at br.edu.ifrn.potigol.parser.potigolParser$Decl_var_multiplaContext.exitRule(potigolParser.java:591)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.exitRule(ParseTreeWalker.java:62)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:38)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:36)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:36)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:36)
        at br.edu.ifrn.potigol.Principal.getListnerFromString(Principal.java:114)
        at br.edu.ifrn.potigol.Principal.getListner(Principal.java:103)
        at br.edu.ifrn.potigol.Principal.main(Principal.java:86)
```

**Comment by leonelsanchesdasilva** [comment]
Em contrapartida:

```
var a, b, c := 1, 2, 3, 4
```

Não retorna resultado algum.
